// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTM6TSQWrbZovRReuc2U-lXaq5WwQBV8',
    appId: '1:714559547171:web:dc57983e36e71e2d550e96',
    messagingSenderId: '714559547171',
    projectId: 'furnihub-f7cc9',
    authDomain: 'furnihub-f7cc9.firebaseapp.com',
    storageBucket: 'furnihub-f7cc9.appspot.com',
    measurementId: 'G-XQEC4FBK5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBih2akx7UbfJXm15QmlmJUibHRksmyWs',
    appId: '1:714559547171:android:9da235f4bc32bde4550e96',
    messagingSenderId: '714559547171',
    projectId: 'furnihub-f7cc9',
    storageBucket: 'furnihub-f7cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PqnKWlV99256Z7IO6ik-3nlPQLAE2HQ',
    appId: '1:714559547171:ios:a5541adedd277d6a550e96',
    messagingSenderId: '714559547171',
    projectId: 'furnihub-f7cc9',
    storageBucket: 'furnihub-f7cc9.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PqnKWlV99256Z7IO6ik-3nlPQLAE2HQ',
    appId: '1:714559547171:ios:a5541adedd277d6a550e96',
    messagingSenderId: '714559547171',
    projectId: 'furnihub-f7cc9',
    storageBucket: 'furnihub-f7cc9.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQTM6TSQWrbZovRReuc2U-lXaq5WwQBV8',
    appId: '1:714559547171:web:49a603b7c80808d0550e96',
    messagingSenderId: '714559547171',
    projectId: 'furnihub-f7cc9',
    authDomain: 'furnihub-f7cc9.firebaseapp.com',
    storageBucket: 'furnihub-f7cc9.appspot.com',
    measurementId: 'G-F6VS65KPSP',
  );

}